Add back link
LBHackney-IT/maintain-my-home-prototype pull request #3
Opened 2017-09-14 13:20 UTC by deberny

During user testing we have discovered a user need to go back to previous page.

Added back links at the end of raise repair pages. This gives the
user the ability to go back and edit their input.

Added improvements to booking call back time logic.

2017-09-14 14:24 UTC, dgmstuart requested changes

2017-09-14 14:24 UTC, dgmstuart commented on app/views/raiserepair/book-appointment-contact.html
> +          <input class="button" type="submit" value="Confirm and book a repair">
I'm not sure about the phrasing "book a repair"

Maybe "Confirm and book this appointment" makes more sense?

2017-09-14 14:24 UTC, dgmstuart commented on app/views/raiserepair/describe-repair-address.html
> +        <p>Something else</p>
Might this be confusing to the resident? Do we need it?

2017-09-14 14:24 UTC, dgmstuart commented on app/views/raiserepair/describe-repair-address.html
> -          {% if data['morningCall'] %}
As discussed, let's remove "school run"

2017-09-14 14:24 UTC, dgmstuart commented on app/views/raiserepair/repair-details.html
> +        <a href="/raiserepair/what-is-problem/">Back to what do you need to be fixed</a>
Might 'what do you need to be fixed?' make more sense in quotes?

2017-09-14 16:24 UTC, deberny commented on app/views/raiserepair/describe-repair-address.html
> -          {% if data['morningCall'] %}
done 👍

2017-09-18 14:37 UTC, dgmstuart approved these changes
Latest changes look good - will merge

2017-09-18 14:38 UTC, merged